title: "muck.blog"
author: "Muckluck"
description: "A little space for written rambles."
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "<!-- readmore -->"
date_format: "%B %d, %Y"
paginate: 5
paginate_path: /page/:num/

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "bond-revisited.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: YouTube, icon: youtube, url: "https://www.youtube.com/c/Muckluck/"}
  - {title: Bluesky, icon: bluesky, url: "https://bsky.app/profile/muck.blog"}
  - {title: Twitch, icon: twitch, url: "https://www.twitch.tv/muckluck"}
  - {title: Discord, icon: discord, url: "https://discord.gg/9y6GwWmX28"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-paginate
